### ISSUE TITLE
Env vars are not passed through to nginx

### ISSUE THREAD

**Issue by dimaip** [psmb/docker-neos-alpine#3]

**Comment by jobee** [comment]
Hey @dimaip ,
I'm currently playing around with your Neos Alpine Docker image and trying to use env vars in some configuration files.

While the following configuration works for the CLI commands...

```yaml
# Configuration/Settings.yaml
Neos:
  Flow:
    persistence:
      backendOptions:
        driver: pdo_mysql
        dbname: '%env:MYSQL_DATABASE%'
        user: '%env:MYSQL_USER%'
        password: '%env:MYSQL_PASSWORD%'
        host: '%env:MYSQL_HOST%'
        port: '%env:MYSQL_PORT%'
```

```yaml
# docker-compose.yml

version: '2.1'
services:
  web:
    build: ./web
    ports:
      - '80:80'
    links:
      - db:db
    env_file: .env
    volumes:
      - /data
...
```

```
# .env

MYSQL_DATABASE=db
MYSQL_USER=admin
MYSQL_PASSWORD=pass
MYSQL_HOST=db
MYSQL_PORT=3306
```

Flow command output:

```
bash-4.3$ ./flow configuration:show --path Neos.Flow.persistence.backendOptions
Configuration "Settings: Neos.Flow.persistence.backendOptions":

driver: pdo_mysql
host: db
dbname: db
user: admin
password: pass
charset: utf8
port: '3306'
```

Its unfortunately not working via web browser. Somehow the env vars are not getting passed through? Like you, we currently use the docker images from Million12 and never had problems with env vars so far. Any clue how to solve this?
